In [1]:
#importing numpy
import numpy as np

In [4]:
#1. dataset
np.random.seed(42)
consumption = np.random.randint(200,600, size=120)
print("consumption: ", consumption)

consumption:  [302 548 470 306 271 388 220 302 321 414 530 287 572 299 559 351 330 349
 508 457 543 493 585 391 476 360 513 221 452 435 544 248 258 369 387 470
 389 374 250 563 254 443 519 330 506 334 220 528 366 473 587 288 515 213
 441 464 545 252 585 539 291 566 463 234 405 280 249 559 587 201 589 253
 305 459 509 390 417 243 361 401 469 550 503 470 414 451 389 495 412 407
 436 537 566 252 479 416 451 387 579 240 356 214 500 264 544 526 208 543
 328 335 262 338 280 591 362 488 578 460 430 240]


In [58]:
#2. Basic Statistics
mean_consumption = np.mean(consumption)
median_consumption = np.median(consumption)
min_consumption = np.min(consumption)
max_consumption = np.max(consumption)
std_consumption = np.std(consumption)

print("Mean Consumption:", (round (mean_consumption, 2)))
print("Median Consumption:", median_consumption)
print("Minimum Consumption:", min_consumption)
print("Maximum Consumption:", max_consumption)
print("Standard Deviation:", (round (std_consumption, 2)))

Mean Consumption: 408.49
Median Consumption: 414.0
Minimum Consumption: 201
Maximum Consumption: 591
Standard Deviation: 115.2


In [59]:
#3. Identify Extremes
highest_day_of_consumption = np.where(consumption == np.max(consumption))[0] + 1
lowest_day_of_consumption = np.where(consumption == np.min(consumption))[0] + 1

print("Highest Day Of Consumption:", highest_day_of_consumption)
print("Lowest Day Of Consumption:", lowest_day_of_consumption)

Highest Day Of Consumption: [114]
Lowest Day Of Consumption: [70]


In [60]:
#4. Monthly Splitting
months = np.array_split(consumption, 4)
per_month = [print(months) for months in months]

[302 548 470 306 271 388 220 302 321 414 530 287 572 299 559 351 330 349
 508 457 543 493 585 391 476 360 513 221 452 435]
[544 248 258 369 387 470 389 374 250 563 254 443 519 330 506 334 220 528
 366 473 587 288 515 213 441 464 545 252 585 539]
[291 566 463 234 405 280 249 559 587 201 589 253 305 459 509 390 417 243
 361 401 469 550 503 470 414 451 389 495 412 407]
[436 537 566 252 479 416 451 387 579 240 356 214 500 264 544 526 208 543
 328 335 262 338 280 591 362 488 578 460 430 240]


In [61]:
#5. Monthly Analysis
print("Total Consumption")
total_consumption = [print(month.sum()) for month in months]
print("\nAverage Daily Consumption")
avg_daily_consumption = [print(round(month.mean(), 2)) for month in months]

Total Consumption
12253
12254
12322
12190

Average Daily Consumption
408.43
408.47
410.73
406.33


In [62]:
#6. Weekly Analysis
weeks = np.array_split(consumption, 7)
per_weeks = [print(week) for week in weeks]

[302 548 470 306 271 388 220 302 321 414 530 287 572 299 559 351 330 349]
[508 457 543 493 585 391 476 360 513 221 452 435 544 248 258 369 387]
[470 389 374 250 563 254 443 519 330 506 334 220 528 366 473 587 288]
[515 213 441 464 545 252 585 539 291 566 463 234 405 280 249 559 587]
[201 589 253 305 459 509 390 417 243 361 401 469 550 503 470 414 451]
[389 495 412 407 436 537 566 252 479 416 451 387 579 240 356 214 500]
[264 544 526 208 543 328 335 262 338 280 591 362 488 578 460 430 240]


In [63]:
#7. Overall Consumption Trend
print("Weekly Totals")
weekly_totals = [print(week.sum()) for week in weeks]
print("\nWeekly Averages")
weekly_avgs = [print(round(week.mean(), 2)) for week in weeks]

Weekly Totals
6819
7240
6894
7188
6985
7116
6777

Weekly Averages
378.83
425.88
405.53
422.82
410.88
418.59
398.65


In [64]:
#8. Anomaly Detection
cumulative_consumption = np.cumsum(consumption)

print("First 10 Cummulative Consumption:")
print(cumulative_consumption[:10])

First 10 Cummulative Consumption:
[ 302  850 1320 1626 1897 2285 2505 2807 3128 3542]


In [65]:
lower_bound = mean_consumption - 2 * std_consumption
upper_bound = mean_consumption + 2 * std_consumption
print(round(lower_bound,2))
print(round(upper_bound,2))
anomaly = np.where((consumption < lower_bound) | (consumption > upper_bound))[0] + 1
print("Anomaly Detection (low/high:)", anomaly)

178.09
638.9
Anomaly Detection (low/high:) []


Summary
The data is contributed with daily values between 200kwh and 600kwh.
The basic statistic such as mean, median, maximum, minimum and standard deviation are calculated to understand the data.
The consumption data is divided into months and weeks to known the total and average of how the electricity was used.
The cumulative electricity was used to calculatethe consumption during the 120 days. Anomaly detection was used to identify the days when the electricity consumption is high or low which is compared with the use of average.